browse: "Browse"
dashboard: "DASHBOARD"
door43_logo: "Door43 Logo"
license: "The content of this page from Door43 is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
popular: "Popular"
recent: "Recent"
recently_updated: "Recently Updated"
search: "Search"
sign_in: "SIGN IN"
source: "Source:"
sub_header: "Open-licensed biblical content"
toggle_nav: "Toggle Navigation"
