name: Publish to S3

on:
  push:
    branches:
      - develop
    release:
      types: [published]

jobs:
  build-n-publish:
    name: Publish to S3
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - run: bundle exec jekyll build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --exclude-from 's3_excludes'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '_site/'
